permalink: pretty

default_lang: 'en'
languages: ['en']


port: 8080
booking_widget_url: https://stanfordcourt.reztrip.com/mobile

url: "https://www.stanfordcourt.com"

data_paginate: 
  per_page: 6
  data: 'blog'
  path: 'blog/page:num'
  pagination_template: 'blog/index.html'
  sort_field: 'date'
  sort_reverse: true
sass:
  style: compressed

#paginate_path: "/page:num/"
markdown: kramdown 
empty_array: []
page_gen:

  - data: 'blog'
    template: 'blog-details'
    dir: 'blog'
  - data: 'category'
    template: 'category'
    dir: 'categories'
  - data: 'events'
    template: 'event-details'
    dir: 'events'
  - data: 'promos'
    template: 'promo-details'
    dir: 'promos'
    

